#   com.carlstahmer.com.estc.recordimport configuration file
#   use this file to set basic configurations.  Settings
#	can be overwritten at run-time, but application will not
#   start if this file is not present in the document root.

#   The directory where the daemon should look for files
#   listendir: /Users/cstahmer/Documents/estc_record_importer/MARCTESTS/estcstar
#   listendir: /Users/cstahmer/Documents/estc_record_importer/MARCTESTS/dev
listendir: /Users/cstahmer/Documents/estc_record_importer_dev
#   The directory where the daemon should write rdf files
#   writedir: /Users/cstahmer/Documents/estc_record_importer_dev/unmatched_RDF
writedir: /Users/cstahmer/Documents/estc_record_importer_dev/testrdf

#   The MARC organization code that will be used as the indentifier for
#   the owner/originator of the converted records
orgcode: estcd

#   The interval that the daemon should wait between processes
runinterval: 5000

#	The SQL Server Name
dbserver: localhost

#	The SQL Databse
#dbname: estcimports
dbname: estcimport_dev

#	The SQL User
dbuser: estcimporter

#	The SQL Password
dbpass: estcpassword

#	Marc Language codes for inScope languages - separated by commas with no spaces
langscope: eng,enm

#	Determines whether to count as in-scope records where scope data
#	determination fields (such as 008) are missing or incomplete or
# 	whether to fail these records. 0 = fail / 1 = pass
liberal: 1

#  the institutional code(s) that are used for records that are ESTC generated
estccodes: estcstar,estcother,CU-RivES

#   Output domain
sitedomain: estc.bl.uk

